# Generated by Django 5.1 on 2024-09-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_admin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=12)),
                ('message', models.TextField()),
            ],
        ),
        
    ]
