# Generated by Django 5.1 on 2024-09-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_admin_user_alter_user_mod_name'),
    ]

    operations = [
     
        migrations.AlterField(
            model_name='user_mod',
            name='name',
            field=models.CharField(max_length=100, serialize=False),
        ),
    ]
