# Generated by Django 5.1 on 2024-09-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_admin_user_remove_user_mod_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_mod',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
