# Generated by Django 5.1 on 2024-09-15 09:16

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_admin_user'),
    ]

operations = [
        migrations.AlterField(
            model_name='user_mod',
            name='name',
            field=models.CharField(max_length=110),
        ),
]
